name: CI_CD_API

on: 
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: bed_pizza
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        
    steps:
      - name: checkout project
        uses: actions/checkout@v4

      - name: set java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cash: 'maven'
          
      - name: build using maven
        run: mvn clean install
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/bed_pizza
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: root

      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: build docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-api:${{ github.sha }} .
      
      - name: push image to dockerhub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-api:${{ github.sha }}
        
      - name: Notify Teams via Webhook Bot
        if: always()
        run: |
          curl -H "Content-Type: application/json" \
           -d '{
               "title": "CI/CD Notification",
               "text": "Workflow ${{ github.workflow }} finished with status: ${{ job.status }} on branch ${{ github.ref }}"
             }' \
             ${{ secrets.TEAMS_WEBHOOK_URL }}

        
